/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateContainerDialog.java
 *
 * Created on 24/04/2012, 21:01:06
 */
package eclis.jcloudsviewer.view;

import eclis.jcloudsviewer.controller.MainFrameControl;
import javax.swing.JTextField;

/**
 *
 * @author Eclis
 */
public class CreateContainerDialog extends javax.swing.JDialog {
    private final  MainFrameControl control;
    /** Creates new form CreateContainerDialog */
    public CreateContainerDialog(MainFrameControl pControl) {
        control = pControl;
        initComponents();
    }

    public JTextField getjTextFieldContainer() {
        return jTextFieldContainer;
    }

    public void setjTextFieldContainer(JTextField jTextFieldContainer) {
        this.jTextFieldContainer = jTextFieldContainer;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldContainer = new javax.swing.JTextField();
        jButtonCreateBucket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Container");

        jLabel1.setText("Container :");

        jButtonCreateBucket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick-icon.png"))); // NOI18N
        jButtonCreateBucket.setText("Create");
        jButtonCreateBucket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateBucketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addComponent(jButtonCreateBucket, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreateBucket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateBucketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateBucketActionPerformed
        control.createContainer();
    }//GEN-LAST:event_jButtonCreateBucketActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateBucket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldContainer;
    // End of variables declaration//GEN-END:variables
}
