/*
 * View.java
 *
 * Created on 20/02/2012, 17:11:28
 */
package eclis.jcloudsviewer.view;

import eclis.jcloudsviewer.controller.MainFrameControl;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTree;

/**
 *
 * @author Eclis
 */
public class MainFrame extends javax.swing.JFrame {

    MainFrameControl mainControl;
    StorageMetadataCellRender cellRender;

    /**
     * Creates new form View
     */
    public MainFrame(MainFrameControl main) {
        mainControl = main;
        initComponents();
        jListContainers.setCellRenderer(new StorageMetadataCellRender());
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        jTreeContents.setRootVisible(false);
    }

    public JList getjListContainers() {
        return jListContainers;
    }

    public void setjListContainers(JList jListContainers) {
        this.jListContainers = jListContainers;
    }

    public JTree getjTreeContents() {
        return jTreeContents;
    }

    public void setjTreeContents(JTree jTreeContents) {
        this.jTreeContents = jTreeContents;
    }

    public JTable getjTableNodes() {
        return jTableNodes;
    }

    public void setjTableNodes(JTable jTableNodes) {
        this.jTableNodes = jTableNodes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneService = new javax.swing.JTabbedPane();
        jPanelBlobStore = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListContainers = new javax.swing.JList();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCreateContainer = new javax.swing.JButton();
        jButtonDeleteContainer = new javax.swing.JButton();
        jButtonRefreshContainer = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTreeContents = new javax.swing.JTree();
        jToolBar5 = new javax.swing.JToolBar();
        jButtonCreateBlob = new javax.swing.JButton();
        jButtonDeleteBlob = new javax.swing.JButton();
        jButtonRefreshContents = new javax.swing.JButton();
        jPanelComputeService = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNodes = new javax.swing.JTable();
        jToolBar4 = new javax.swing.JToolBar();
        jButtonCreateNode = new javax.swing.JButton();
        jButtonDeleteNode = new javax.swing.JButton();
        jButtonRefreshNode = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        NCMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JClouds Viewer");
        setBounds(new java.awt.Rectangle(350, 100, 1024, 768));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelBlobStore.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jListContainers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListContainers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListContainersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListContainers);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jButtonCreateContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-icon.png"))); // NOI18N
        jButtonCreateContainer.setText("Create Container");
        jButtonCreateContainer.setFocusable(false);
        jButtonCreateContainer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCreateContainer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCreateContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateContainerActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCreateContainer);

        jButtonDeleteContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-icon.png"))); // NOI18N
        jButtonDeleteContainer.setText("Delete Container");
        jButtonDeleteContainer.setFocusable(false);
        jButtonDeleteContainer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDeleteContainer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeleteContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteContainerActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDeleteContainer);

        jButtonRefreshContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh-icon.png"))); // NOI18N
        jButtonRefreshContainer.setText("Refresh");
        jButtonRefreshContainer.setFocusable(false);
        jButtonRefreshContainer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRefreshContainer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRefreshContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshContainerActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRefreshContainer);

        jPanel5.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setLeftComponent(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeContents.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jTreeContents);

        jPanel6.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jToolBar5.setRollover(true);

        jButtonCreateBlob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-icon.png"))); // NOI18N
        jButtonCreateBlob.setText("Create Blob");
        jButtonCreateBlob.setFocusable(false);
        jButtonCreateBlob.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCreateBlob.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCreateBlob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateBlobActionPerformed(evt);
            }
        });
        jToolBar5.add(jButtonCreateBlob);

        jButtonDeleteBlob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-icon.png"))); // NOI18N
        jButtonDeleteBlob.setText("Delete Blob");
        jButtonDeleteBlob.setFocusable(false);
        jButtonDeleteBlob.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDeleteBlob.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeleteBlob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBlobActionPerformed(evt);
            }
        });
        jToolBar5.add(jButtonDeleteBlob);

        jButtonRefreshContents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh-icon.png"))); // NOI18N
        jButtonRefreshContents.setText("Refresh");
        jButtonRefreshContents.setFocusable(false);
        jButtonRefreshContents.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRefreshContents.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRefreshContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshContentsActionPerformed(evt);
            }
        });
        jToolBar5.add(jButtonRefreshContents);

        jPanel6.add(jToolBar5, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setRightComponent(jPanel6);

        jPanelBlobStore.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jTabbedPaneService.addTab("BlobStore", jPanelBlobStore);

        jPanelComputeService.setLayout(new java.awt.BorderLayout());

        jTableNodes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ProviderId", "Name", "Location", "Operating System", "State", "IP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableNodes);

        jPanelComputeService.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jToolBar4.setRollover(true);

        jButtonCreateNode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-icon.png"))); // NOI18N
        jButtonCreateNode.setText("Create Node");
        jButtonCreateNode.setFocusable(false);
        jButtonCreateNode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCreateNode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCreateNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateNodeActionPerformed(evt);
            }
        });
        jToolBar4.add(jButtonCreateNode);

        jButtonDeleteNode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-icon.png"))); // NOI18N
        jButtonDeleteNode.setText("Delete Node");
        jButtonDeleteNode.setFocusable(false);
        jButtonDeleteNode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDeleteNode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeleteNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteNodeActionPerformed(evt);
            }
        });
        jToolBar4.add(jButtonDeleteNode);

        jButtonRefreshNode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh-icon.png"))); // NOI18N
        jButtonRefreshNode.setText("Refresh");
        jButtonRefreshNode.setFocusable(false);
        jButtonRefreshNode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRefreshNode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRefreshNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshNodeActionPerformed(evt);
            }
        });
        jToolBar4.add(jButtonRefreshNode);

        jPanelComputeService.add(jToolBar4, java.awt.BorderLayout.PAGE_START);

        jTabbedPaneService.addTab("ComputeService", jPanelComputeService);

        getContentPane().add(jTabbedPaneService, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        NCMenuItem.setMnemonic('o');
        NCMenuItem.setText("New Connection");
        NCMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NCMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(NCMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void NCMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCMenuItemActionPerformed
    }//GEN-LAST:event_NCMenuItemActionPerformed

    private void jButtonCreateContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateContainerActionPerformed
        mainControl.openDialogCreateContainer();
    }//GEN-LAST:event_jButtonCreateContainerActionPerformed

    private void jListContainersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListContainersMouseClicked
        mainControl.listContents();
        jTreeContents.setCellRenderer(new StorageMetadataTreeCellRender());
    }//GEN-LAST:event_jListContainersMouseClicked

    private void jButtonDeleteContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteContainerActionPerformed
        mainControl.deleteContainer();
    }//GEN-LAST:event_jButtonDeleteContainerActionPerformed

    private void jButtonRefreshContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshContainerActionPerformed
        mainControl.listContainers();
    }//GEN-LAST:event_jButtonRefreshContainerActionPerformed

    private void jButtonRefreshContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshContentsActionPerformed
        mainControl.listContents();
    }//GEN-LAST:event_jButtonRefreshContentsActionPerformed

    private void jButtonCreateBlobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateBlobActionPerformed
        mainControl.openDialogCreateBlob();
    }//GEN-LAST:event_jButtonCreateBlobActionPerformed

    private void jButtonDeleteBlobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBlobActionPerformed
        mainControl.deleteBlob();
    }//GEN-LAST:event_jButtonDeleteBlobActionPerformed

    private void jButtonDeleteNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteNodeActionPerformed
        mainControl.deleteNode();
    }//GEN-LAST:event_jButtonDeleteNodeActionPerformed

    private void jButtonRefreshNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshNodeActionPerformed
        mainControl.listNodes();
    }//GEN-LAST:event_jButtonRefreshNodeActionPerformed

    private void jButtonCreateNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateNodeActionPerformed
        mainControl.openDialogCreateNode();
    }//GEN-LAST:event_jButtonCreateNodeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NCMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButtonCreateBlob;
    private javax.swing.JButton jButtonCreateContainer;
    private javax.swing.JButton jButtonCreateNode;
    private javax.swing.JButton jButtonDeleteBlob;
    private javax.swing.JButton jButtonDeleteContainer;
    private javax.swing.JButton jButtonDeleteNode;
    private javax.swing.JButton jButtonRefreshContainer;
    private javax.swing.JButton jButtonRefreshContents;
    private javax.swing.JButton jButtonRefreshNode;
    private javax.swing.JList jListContainers;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBlobStore;
    private javax.swing.JPanel jPanelComputeService;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPaneService;
    private javax.swing.JTable jTableNodes;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JTree jTreeContents;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
}
